name: pixgraphy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  fpdart: ^1.0.0
  json_annotation: ^4.7.0
  google_sign_in: ^6.1.4
  go_router: ^10.0.0
  shared_preferences: ^2.0.15
  image_picker: ^1.0.1
  image: ^4.0.3
  uuid: ^3.0.7
  firebase_storage: ^11.0.10
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.2.1
  http: ^1.1.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true

  assets:
    - assets/images/default_pro_pic.png
    - assets/images/landing_bg_dark.png
    - assets/images/landing_bg_light.png
 