// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSgwppaSnc77kbjO1UkFmvE8BPX2IZV4',
    appId: '1:662240066334:web:ab8fa2b1c9387b18ffe70f',
    messagingSenderId: '662240066334',
    projectId: 'pixgraphy-7010d',
    authDomain: 'pixgraphy-7010d.firebaseapp.com',
    storageBucket: 'pixgraphy-7010d.appspot.com',
    measurementId: 'G-R6S5H3ZJWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA773i84aecCdUmM1B4ALcgyYse85Sj54c',
    appId: '1:662240066334:android:e14e302423902ab7ffe70f',
    messagingSenderId: '662240066334',
    projectId: 'pixgraphy-7010d',
    storageBucket: 'pixgraphy-7010d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVnO5qILrGsi8U23WvqciLRq3elLxk2SE',
    appId: '1:662240066334:ios:a18952efbf4700f2ffe70f',
    messagingSenderId: '662240066334',
    projectId: 'pixgraphy-7010d',
    storageBucket: 'pixgraphy-7010d.appspot.com',
    androidClientId: '662240066334-4cvf5uu2nrmukggt1g169td2tu3po6hm.apps.googleusercontent.com',
    iosClientId: '662240066334-p3a2h4vkn1ibo7cbi510fd6k0sro0mj6.apps.googleusercontent.com',
    iosBundleId: 'am.pixgraphy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVnO5qILrGsi8U23WvqciLRq3elLxk2SE',
    appId: '1:662240066334:ios:a18952efbf4700f2ffe70f',
    messagingSenderId: '662240066334',
    projectId: 'pixgraphy-7010d',
    storageBucket: 'pixgraphy-7010d.appspot.com',
    androidClientId: '662240066334-4cvf5uu2nrmukggt1g169td2tu3po6hm.apps.googleusercontent.com',
    iosClientId: '662240066334-p3a2h4vkn1ibo7cbi510fd6k0sro0mj6.apps.googleusercontent.com',
    iosBundleId: 'am.pixgraphy',
  );
}
